name: バグ報告
description: どういう壊れ方をしたのか
labels: [bug]
assignees: nodokaha
body:
  - type: textarea
    id: Describe
    attributes:
      label: バグ概要
      description: 詳細なバグ状況を記載
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: どのようにして引き起こすのか
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 起こった現象
      description: 一体何が起こったのかを詳細に
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: 状況に関連する画像の提示
    validations:
      required: false
  - type: textarea
    id: buildinfo
    attributes:
      label: ビルド情報
      description: 'メニューでSettings > Developer のあと "Copy Build Info"をコピペ。もし見えなかったら"Build & Environment"を有効に'
      placeholder: 'Version: ...  Unity: ...  Platform: ...  Mode: ...  Build GUID: ...'
    validations:
      required: true
  - type: textarea
    id: log-files
    attributes:
      label: ログファイル
      description: ログを貼り付ける
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: 備考
      description: 追加で伝えたいことあれば
    validations:
      required: false
