name: Feature Request
description: Please submit your desired enhancement for the framework.
labels: [enhancement]
assignees: nodokaha
body:
  - type: textarea
    id: problem
    attributes:
      label: あなたにとって問題であったこと
      description: このPRが提案されるべき理由や、要望の詳細
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 解決策
      description: 要望や問題への解決として有効である理由も含めて、解決となる概要
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: さらなる問題との関連性
      description: このPRがその他に関連した問題について言及する場合は記載
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: 備考
      description: その他書いておきたいことあれば
    validations:
      required: false
